package android.system;

public final class OsConstants
{
    public static final int AF_INET;
    public static final int AF_INET6;
    public static final int AF_UNIX;
    public static final int AF_UNSPEC;
    public static final int AI_ADDRCONFIG;
    public static final int AI_ALL;
    public static final int AI_CANONNAME;
    public static final int AI_NUMERICHOST;
    public static final int AI_NUMERICSERV;
    public static final int AI_PASSIVE;
    public static final int AI_V4MAPPED;
    public static final int CAP_AUDIT_CONTROL;
    public static final int CAP_AUDIT_WRITE;
    public static final int CAP_BLOCK_SUSPEND;
    public static final int CAP_CHOWN;
    public static final int CAP_DAC_OVERRIDE;
    public static final int CAP_DAC_READ_SEARCH;
    public static final int CAP_FOWNER;
    public static final int CAP_FSETID;
    public static final int CAP_IPC_LOCK;
    public static final int CAP_IPC_OWNER;
    public static final int CAP_KILL;
    public static final int CAP_LAST_CAP;
    public static final int CAP_LEASE;
    public static final int CAP_LINUX_IMMUTABLE;
    public static final int CAP_MAC_ADMIN;
    public static final int CAP_MAC_OVERRIDE;
    public static final int CAP_MKNOD;
    public static final int CAP_NET_ADMIN;
    public static final int CAP_NET_BIND_SERVICE;
    public static final int CAP_NET_BROADCAST;
    public static final int CAP_NET_RAW;
    public static final int CAP_SETFCAP;
    public static final int CAP_SETGID;
    public static final int CAP_SETPCAP;
    public static final int CAP_SETUID;
    public static final int CAP_SYSLOG;
    public static final int CAP_SYS_ADMIN;
    public static final int CAP_SYS_BOOT;
    public static final int CAP_SYS_CHROOT;
    public static final int CAP_SYS_MODULE;
    public static final int CAP_SYS_NICE;
    public static final int CAP_SYS_PACCT;
    public static final int CAP_SYS_PTRACE;
    public static final int CAP_SYS_RAWIO;
    public static final int CAP_SYS_RESOURCE;
    public static final int CAP_SYS_TIME;
    public static final int CAP_SYS_TTY_CONFIG;
    public static final int CAP_WAKE_ALARM;
    public static final int E2BIG;
    public static final int EACCES;
    public static final int EADDRINUSE;
    public static final int EADDRNOTAVAIL;
    public static final int EAFNOSUPPORT;
    public static final int EAGAIN;
    public static final int EAI_AGAIN;
    public static final int EAI_BADFLAGS;
    public static final int EAI_FAIL;
    public static final int EAI_FAMILY;
    public static final int EAI_MEMORY;
    public static final int EAI_NODATA;
    public static final int EAI_NONAME;
    public static final int EAI_OVERFLOW;
    public static final int EAI_SERVICE;
    public static final int EAI_SOCKTYPE;
    public static final int EAI_SYSTEM;
    public static final int EALREADY;
    public static final int EBADF;
    public static final int EBADMSG;
    public static final int EBUSY;
    public static final int ECANCELED;
    public static final int ECHILD;
    public static final int ECONNABORTED;
    public static final int ECONNREFUSED;
    public static final int ECONNRESET;
    public static final int EDEADLK;
    public static final int EDESTADDRREQ;
    public static final int EDOM;
    public static final int EDQUOT;
    public static final int EEXIST;
    public static final int EFAULT;
    public static final int EFBIG;
    public static final int EHOSTUNREACH;
    public static final int EIDRM;
    public static final int EILSEQ;
    public static final int EINPROGRESS;
    public static final int EINTR;
    public static final int EINVAL;
    public static final int EIO;
    public static final int EISCONN;
    public static final int EISDIR;
    public static final int ELOOP;
    public static final int EMFILE;
    public static final int EMLINK;
    public static final int EMSGSIZE;
    public static final int EMULTIHOP;
    public static final int ENAMETOOLONG;
    public static final int ENETDOWN;
    public static final int ENETRESET;
    public static final int ENETUNREACH;
    public static final int ENFILE;
    public static final int ENOBUFS;
    public static final int ENODATA;
    public static final int ENODEV;
    public static final int ENOENT;
    public static final int ENOEXEC;
    public static final int ENOLCK;
    public static final int ENOLINK;
    public static final int ENOMEM;
    public static final int ENOMSG;
    public static final int ENOPROTOOPT;
    public static final int ENOSPC;
    public static final int ENOSR;
    public static final int ENOSTR;
    public static final int ENOSYS;
    public static final int ENOTCONN;
    public static final int ENOTDIR;
    public static final int ENOTEMPTY;
    public static final int ENOTSOCK;
    public static final int ENOTSUP;
    public static final int ENOTTY;
    public static final int ENXIO;
    public static final int EOPNOTSUPP;
    public static final int EOVERFLOW;
    public static final int EPERM;
    public static final int EPIPE;
    public static final int EPROTO;
    public static final int EPROTONOSUPPORT;
    public static final int EPROTOTYPE;
    public static final int ERANGE;
    public static final int EROFS;
    public static final int ESPIPE;
    public static final int ESRCH;
    public static final int ESTALE;
    public static final int ETIME;
    public static final int ETIMEDOUT;
    public static final int ETXTBSY;
    public static final int EXDEV;
    public static final int EXIT_FAILURE;
    public static final int EXIT_SUCCESS;
    public static final int FD_CLOEXEC;
    public static final int FIONREAD;
    public static final int F_DUPFD;
    public static final int F_DUPFD_CLOEXEC;
    public static final int F_GETFD;
    public static final int F_GETFL;
    public static final int F_GETLK;
    public static final int F_GETLK64;
    public static final int F_GETOWN;
    public static final int F_OK;
    public static final int F_RDLCK;
    public static final int F_SETFD;
    public static final int F_SETFL;
    public static final int F_SETLK;
    public static final int F_SETLK64;
    public static final int F_SETLKW;
    public static final int F_SETLKW64;
    public static final int F_SETOWN;
    public static final int F_UNLCK;
    public static final int F_WRLCK;
    public static final int IFA_F_DADFAILED;
    public static final int IFA_F_DEPRECATED;
    public static final int IFA_F_HOMEADDRESS;
    public static final int IFA_F_NODAD;
    public static final int IFA_F_OPTIMISTIC;
    public static final int IFA_F_PERMANENT;
    public static final int IFA_F_SECONDARY;
    public static final int IFA_F_TEMPORARY;
    public static final int IFA_F_TENTATIVE;
    public static final int IFF_ALLMULTI;
    public static final int IFF_AUTOMEDIA;
    public static final int IFF_BROADCAST;
    public static final int IFF_DEBUG;
    public static final int IFF_DYNAMIC;
    public static final int IFF_LOOPBACK;
    public static final int IFF_MASTER;
    public static final int IFF_MULTICAST;
    public static final int IFF_NOARP;
    public static final int IFF_NOTRAILERS;
    public static final int IFF_POINTOPOINT;
    public static final int IFF_PORTSEL;
    public static final int IFF_PROMISC;
    public static final int IFF_RUNNING;
    public static final int IFF_SLAVE;
    public static final int IFF_UP;
    public static final int IPPROTO_ICMP;
    public static final int IPPROTO_ICMPV6;
    public static final int IPPROTO_IP;
    public static final int IPPROTO_IPV6;
    public static final int IPPROTO_RAW;
    public static final int IPPROTO_TCP;
    public static final int IPPROTO_UDP;
    public static final int IPV6_CHECKSUM;
    public static final int IPV6_MULTICAST_HOPS;
    public static final int IPV6_MULTICAST_IF;
    public static final int IPV6_MULTICAST_LOOP;
    public static final int IPV6_RECVDSTOPTS;
    public static final int IPV6_RECVHOPLIMIT;
    public static final int IPV6_RECVHOPOPTS;
    public static final int IPV6_RECVPKTINFO;
    public static final int IPV6_RECVRTHDR;
    public static final int IPV6_RECVTCLASS;
    public static final int IPV6_TCLASS;
    public static final int IPV6_UNICAST_HOPS;
    public static final int IPV6_V6ONLY;
    public static final int IP_MULTICAST_IF;
    public static final int IP_MULTICAST_LOOP;
    public static final int IP_MULTICAST_TTL;
    public static final int IP_TOS;
    public static final int IP_TTL;
    public static final int MAP_FIXED;
    public static final int MAP_PRIVATE;
    public static final int MAP_SHARED;
    public static final int MCAST_BLOCK_SOURCE;
    public static final int MCAST_JOIN_GROUP;
    public static final int MCAST_JOIN_SOURCE_GROUP;
    public static final int MCAST_LEAVE_GROUP;
    public static final int MCAST_LEAVE_SOURCE_GROUP;
    public static final int MCAST_UNBLOCK_SOURCE;
    public static final int MCL_CURRENT;
    public static final int MCL_FUTURE;
    public static final int MSG_CTRUNC;
    public static final int MSG_DONTROUTE;
    public static final int MSG_EOR;
    public static final int MSG_OOB;
    public static final int MSG_PEEK;
    public static final int MSG_TRUNC;
    public static final int MSG_WAITALL;
    public static final int MS_ASYNC;
    public static final int MS_INVALIDATE;
    public static final int MS_SYNC;
    public static final int NI_DGRAM;
    public static final int NI_NAMEREQD;
    public static final int NI_NOFQDN;
    public static final int NI_NUMERICHOST;
    public static final int NI_NUMERICSERV;
    public static final int O_ACCMODE;
    public static final int O_APPEND;
    public static final int O_CLOEXEC;
    public static final int O_CREAT;
    public static final int O_DSYNC;
    public static final int O_EXCL;
    public static final int O_NOCTTY;
    public static final int O_NOFOLLOW;
    public static final int O_NONBLOCK;
    public static final int O_RDONLY;
    public static final int O_RDWR;
    public static final int O_SYNC;
    public static final int O_TRUNC;
    public static final int O_WRONLY;
    public static final int POLLERR;
    public static final int POLLHUP;
    public static final int POLLIN;
    public static final int POLLNVAL;
    public static final int POLLOUT;
    public static final int POLLPRI;
    public static final int POLLRDBAND;
    public static final int POLLRDNORM;
    public static final int POLLWRBAND;
    public static final int POLLWRNORM;
    public static final int PROT_EXEC;
    public static final int PROT_NONE;
    public static final int PROT_READ;
    public static final int PROT_WRITE;
    public static final int PR_GET_DUMPABLE;
    public static final int PR_SET_DUMPABLE;
    public static final int PR_SET_NO_NEW_PRIVS;
    public static final int RT_SCOPE_HOST;
    public static final int RT_SCOPE_LINK;
    public static final int RT_SCOPE_NOWHERE;
    public static final int RT_SCOPE_SITE;
    public static final int RT_SCOPE_UNIVERSE;
    public static final int R_OK;
    public static final int SEEK_CUR;
    public static final int SEEK_END;
    public static final int SEEK_SET;
    public static final int SHUT_RD;
    public static final int SHUT_RDWR;
    public static final int SHUT_WR;
    public static final int SIGABRT;
    public static final int SIGALRM;
    public static final int SIGBUS;
    public static final int SIGCHLD;
    public static final int SIGCONT;
    public static final int SIGFPE;
    public static final int SIGHUP;
    public static final int SIGILL;
    public static final int SIGINT;
    public static final int SIGIO;
    public static final int SIGKILL;
    public static final int SIGPIPE;
    public static final int SIGPROF;
    public static final int SIGPWR;
    public static final int SIGQUIT;
    public static final int SIGRTMAX;
    public static final int SIGRTMIN;
    public static final int SIGSEGV;
    public static final int SIGSTKFLT;
    public static final int SIGSTOP;
    public static final int SIGSYS;
    public static final int SIGTERM;
    public static final int SIGTRAP;
    public static final int SIGTSTP;
    public static final int SIGTTIN;
    public static final int SIGTTOU;
    public static final int SIGURG;
    public static final int SIGUSR1;
    public static final int SIGUSR2;
    public static final int SIGVTALRM;
    public static final int SIGWINCH;
    public static final int SIGXCPU;
    public static final int SIGXFSZ;
    public static final int SIOCGIFADDR;
    public static final int SIOCGIFBRDADDR;
    public static final int SIOCGIFDSTADDR;
    public static final int SIOCGIFNETMASK;
    public static final int SOCK_DGRAM;
    public static final int SOCK_RAW;
    public static final int SOCK_SEQPACKET;
    public static final int SOCK_STREAM;
    public static final int SOL_SOCKET;
    public static final int SO_BINDTODEVICE;
    public static final int SO_BROADCAST;
    public static final int SO_DEBUG;
    public static final int SO_DONTROUTE;
    public static final int SO_ERROR;
    public static final int SO_KEEPALIVE;
    public static final int SO_LINGER;
    public static final int SO_OOBINLINE;
    public static final int SO_PASSCRED;
    public static final int SO_PEERCRED;
    public static final int SO_RCVBUF;
    public static final int SO_RCVLOWAT;
    public static final int SO_RCVTIMEO;
    public static final int SO_REUSEADDR;
    public static final int SO_SNDBUF;
    public static final int SO_SNDLOWAT;
    public static final int SO_SNDTIMEO;
    public static final int SO_TYPE;
    public static final int STDERR_FILENO;
    public static final int STDIN_FILENO;
    public static final int STDOUT_FILENO;
    public static final int ST_MANDLOCK;
    public static final int ST_NOATIME;
    public static final int ST_NODEV;
    public static final int ST_NODIRATIME;
    public static final int ST_NOEXEC;
    public static final int ST_NOSUID;
    public static final int ST_RDONLY;
    public static final int ST_RELATIME;
    public static final int ST_SYNCHRONOUS;
    public static final int S_IFBLK;
    public static final int S_IFCHR;
    public static final int S_IFDIR;
    public static final int S_IFIFO;
    public static final int S_IFLNK;
    public static final int S_IFMT;
    public static final int S_IFREG;
    public static final int S_IFSOCK;
    public static final int S_IRGRP;
    public static final int S_IROTH;
    public static final int S_IRUSR;
    public static final int S_IRWXG;
    public static final int S_IRWXO;
    public static final int S_IRWXU;
    public static final int S_ISGID;
    public static final int S_ISUID;
    public static final int S_ISVTX;
    public static final int S_IWGRP;
    public static final int S_IWOTH;
    public static final int S_IWUSR;
    public static final int S_IXGRP;
    public static final int S_IXOTH;
    public static final int S_IXUSR;
    public static final int TCP_NODELAY;
    public static final int TCP_USER_TIMEOUT;
    public static final int WCONTINUED;
    public static final int WEXITED;
    public static final int WNOHANG;
    public static final int WNOWAIT;
    public static final int WSTOPPED;
    public static final int WUNTRACED;
    public static final int W_OK;
    public static final int X_OK;
    public static final int _SC_2_CHAR_TERM;
    public static final int _SC_2_C_BIND;
    public static final int _SC_2_C_DEV;
    public static final int _SC_2_C_VERSION;
    public static final int _SC_2_FORT_DEV;
    public static final int _SC_2_FORT_RUN;
    public static final int _SC_2_LOCALEDEF;
    public static final int _SC_2_SW_DEV;
    public static final int _SC_2_UPE;
    public static final int _SC_2_VERSION;
    public static final int _SC_AIO_LISTIO_MAX;
    public static final int _SC_AIO_MAX;
    public static final int _SC_AIO_PRIO_DELTA_MAX;
    public static final int _SC_ARG_MAX;
    public static final int _SC_ASYNCHRONOUS_IO;
    public static final int _SC_ATEXIT_MAX;
    public static final int _SC_AVPHYS_PAGES;
    public static final int _SC_BC_BASE_MAX;
    public static final int _SC_BC_DIM_MAX;
    public static final int _SC_BC_SCALE_MAX;
    public static final int _SC_BC_STRING_MAX;
    public static final int _SC_CHILD_MAX;
    public static final int _SC_CLK_TCK;
    public static final int _SC_COLL_WEIGHTS_MAX;
    public static final int _SC_DELAYTIMER_MAX;
    public static final int _SC_EXPR_NEST_MAX;
    public static final int _SC_FSYNC;
    public static final int _SC_GETGR_R_SIZE_MAX;
    public static final int _SC_GETPW_R_SIZE_MAX;
    public static final int _SC_IOV_MAX;
    public static final int _SC_JOB_CONTROL;
    public static final int _SC_LINE_MAX;
    public static final int _SC_LOGIN_NAME_MAX;
    public static final int _SC_MAPPED_FILES;
    public static final int _SC_MEMLOCK;
    public static final int _SC_MEMLOCK_RANGE;
    public static final int _SC_MEMORY_PROTECTION;
    public static final int _SC_MESSAGE_PASSING;
    public static final int _SC_MQ_OPEN_MAX;
    public static final int _SC_MQ_PRIO_MAX;
    public static final int _SC_NGROUPS_MAX;
    public static final int _SC_NPROCESSORS_CONF;
    public static final int _SC_NPROCESSORS_ONLN;
    public static final int _SC_OPEN_MAX;
    public static final int _SC_PAGESIZE;
    public static final int _SC_PAGE_SIZE;
    public static final int _SC_PASS_MAX;
    public static final int _SC_PHYS_PAGES;
    public static final int _SC_PRIORITIZED_IO;
    public static final int _SC_PRIORITY_SCHEDULING;
    public static final int _SC_REALTIME_SIGNALS;
    public static final int _SC_RE_DUP_MAX;
    public static final int _SC_RTSIG_MAX;
    public static final int _SC_SAVED_IDS;
    public static final int _SC_SEMAPHORES;
    public static final int _SC_SEM_NSEMS_MAX;
    public static final int _SC_SEM_VALUE_MAX;
    public static final int _SC_SHARED_MEMORY_OBJECTS;
    public static final int _SC_SIGQUEUE_MAX;
    public static final int _SC_STREAM_MAX;
    public static final int _SC_SYNCHRONIZED_IO;
    public static final int _SC_THREADS;
    public static final int _SC_THREAD_ATTR_STACKADDR;
    public static final int _SC_THREAD_ATTR_STACKSIZE;
    public static final int _SC_THREAD_DESTRUCTOR_ITERATIONS;
    public static final int _SC_THREAD_KEYS_MAX;
    public static final int _SC_THREAD_PRIORITY_SCHEDULING;
    public static final int _SC_THREAD_PRIO_INHERIT;
    public static final int _SC_THREAD_PRIO_PROTECT;
    public static final int _SC_THREAD_SAFE_FUNCTIONS;
    public static final int _SC_THREAD_STACK_MIN;
    public static final int _SC_THREAD_THREADS_MAX;
    public static final int _SC_TIMERS;
    public static final int _SC_TIMER_MAX;
    public static final int _SC_TTY_NAME_MAX;
    public static final int _SC_TZNAME_MAX;
    public static final int _SC_VERSION;
    public static final int _SC_XBS5_ILP32_OFF32;
    public static final int _SC_XBS5_ILP32_OFFBIG;
    public static final int _SC_XBS5_LP64_OFF64;
    public static final int _SC_XBS5_LPBIG_OFFBIG;
    public static final int _SC_XOPEN_CRYPT;
    public static final int _SC_XOPEN_ENH_I18N;
    public static final int _SC_XOPEN_LEGACY;
    public static final int _SC_XOPEN_REALTIME;
    public static final int _SC_XOPEN_REALTIME_THREADS;
    public static final int _SC_XOPEN_SHM;
    public static final int _SC_XOPEN_UNIX;
    public static final int _SC_XOPEN_VERSION;
    public static final int _SC_XOPEN_XCU_VERSION;
    
    OsConstants() {
        throw new RuntimeException("Stub!");
    }
    
    public static boolean S_ISBLK(final int mode) {
        throw new RuntimeException("Stub!");
    }
    
    public static boolean S_ISCHR(final int mode) {
        throw new RuntimeException("Stub!");
    }
    
    public static boolean S_ISDIR(final int mode) {
        throw new RuntimeException("Stub!");
    }
    
    public static boolean S_ISFIFO(final int mode) {
        throw new RuntimeException("Stub!");
    }
    
    public static boolean S_ISREG(final int mode) {
        throw new RuntimeException("Stub!");
    }
    
    public static boolean S_ISLNK(final int mode) {
        throw new RuntimeException("Stub!");
    }
    
    public static boolean S_ISSOCK(final int mode) {
        throw new RuntimeException("Stub!");
    }
    
    public static int WEXITSTATUS(final int status) {
        throw new RuntimeException("Stub!");
    }
    
    public static boolean WCOREDUMP(final int status) {
        throw new RuntimeException("Stub!");
    }
    
    public static int WTERMSIG(final int status) {
        throw new RuntimeException("Stub!");
    }
    
    public static int WSTOPSIG(final int status) {
        throw new RuntimeException("Stub!");
    }
    
    public static boolean WIFEXITED(final int status) {
        throw new RuntimeException("Stub!");
    }
    
    public static boolean WIFSTOPPED(final int status) {
        throw new RuntimeException("Stub!");
    }
    
    public static boolean WIFSIGNALED(final int status) {
        throw new RuntimeException("Stub!");
    }
    
    public static String gaiName(final int error) {
        throw new RuntimeException("Stub!");
    }
    
    public static String errnoName(final int errno) {
        throw new RuntimeException("Stub!");
    }
    
    static {
        AF_INET = 0;
        AF_INET6 = 0;
        AF_UNIX = 0;
        AF_UNSPEC = 0;
        AI_ADDRCONFIG = 0;
        AI_ALL = 0;
        AI_CANONNAME = 0;
        AI_NUMERICHOST = 0;
        AI_NUMERICSERV = 0;
        AI_PASSIVE = 0;
        AI_V4MAPPED = 0;
        CAP_AUDIT_CONTROL = 0;
        CAP_AUDIT_WRITE = 0;
        CAP_BLOCK_SUSPEND = 0;
        CAP_CHOWN = 0;
        CAP_DAC_OVERRIDE = 0;
        CAP_DAC_READ_SEARCH = 0;
        CAP_FOWNER = 0;
        CAP_FSETID = 0;
        CAP_IPC_LOCK = 0;
        CAP_IPC_OWNER = 0;
        CAP_KILL = 0;
        CAP_LAST_CAP = 0;
        CAP_LEASE = 0;
        CAP_LINUX_IMMUTABLE = 0;
        CAP_MAC_ADMIN = 0;
        CAP_MAC_OVERRIDE = 0;
        CAP_MKNOD = 0;
        CAP_NET_ADMIN = 0;
        CAP_NET_BIND_SERVICE = 0;
        CAP_NET_BROADCAST = 0;
        CAP_NET_RAW = 0;
        CAP_SETFCAP = 0;
        CAP_SETGID = 0;
        CAP_SETPCAP = 0;
        CAP_SETUID = 0;
        CAP_SYSLOG = 0;
        CAP_SYS_ADMIN = 0;
        CAP_SYS_BOOT = 0;
        CAP_SYS_CHROOT = 0;
        CAP_SYS_MODULE = 0;
        CAP_SYS_NICE = 0;
        CAP_SYS_PACCT = 0;
        CAP_SYS_PTRACE = 0;
        CAP_SYS_RAWIO = 0;
        CAP_SYS_RESOURCE = 0;
        CAP_SYS_TIME = 0;
        CAP_SYS_TTY_CONFIG = 0;
        CAP_WAKE_ALARM = 0;
        E2BIG = 0;
        EACCES = 0;
        EADDRINUSE = 0;
        EADDRNOTAVAIL = 0;
        EAFNOSUPPORT = 0;
        EAGAIN = 0;
        EAI_AGAIN = 0;
        EAI_BADFLAGS = 0;
        EAI_FAIL = 0;
        EAI_FAMILY = 0;
        EAI_MEMORY = 0;
        EAI_NODATA = 0;
        EAI_NONAME = 0;
        EAI_OVERFLOW = 0;
        EAI_SERVICE = 0;
        EAI_SOCKTYPE = 0;
        EAI_SYSTEM = 0;
        EALREADY = 0;
        EBADF = 0;
        EBADMSG = 0;
        EBUSY = 0;
        ECANCELED = 0;
        ECHILD = 0;
        ECONNABORTED = 0;
        ECONNREFUSED = 0;
        ECONNRESET = 0;
        EDEADLK = 0;
        EDESTADDRREQ = 0;
        EDOM = 0;
        EDQUOT = 0;
        EEXIST = 0;
        EFAULT = 0;
        EFBIG = 0;
        EHOSTUNREACH = 0;
        EIDRM = 0;
        EILSEQ = 0;
        EINPROGRESS = 0;
        EINTR = 0;
        EINVAL = 0;
        EIO = 0;
        EISCONN = 0;
        EISDIR = 0;
        ELOOP = 0;
        EMFILE = 0;
        EMLINK = 0;
        EMSGSIZE = 0;
        EMULTIHOP = 0;
        ENAMETOOLONG = 0;
        ENETDOWN = 0;
        ENETRESET = 0;
        ENETUNREACH = 0;
        ENFILE = 0;
        ENOBUFS = 0;
        ENODATA = 0;
        ENODEV = 0;
        ENOENT = 0;
        ENOEXEC = 0;
        ENOLCK = 0;
        ENOLINK = 0;
        ENOMEM = 0;
        ENOMSG = 0;
        ENOPROTOOPT = 0;
        ENOSPC = 0;
        ENOSR = 0;
        ENOSTR = 0;
        ENOSYS = 0;
        ENOTCONN = 0;
        ENOTDIR = 0;
        ENOTEMPTY = 0;
        ENOTSOCK = 0;
        ENOTSUP = 0;
        ENOTTY = 0;
        ENXIO = 0;
        EOPNOTSUPP = 0;
        EOVERFLOW = 0;
        EPERM = 0;
        EPIPE = 0;
        EPROTO = 0;
        EPROTONOSUPPORT = 0;
        EPROTOTYPE = 0;
        ERANGE = 0;
        EROFS = 0;
        ESPIPE = 0;
        ESRCH = 0;
        ESTALE = 0;
        ETIME = 0;
        ETIMEDOUT = 0;
        ETXTBSY = 0;
        EXDEV = 0;
        EXIT_FAILURE = 0;
        EXIT_SUCCESS = 0;
        FD_CLOEXEC = 0;
        FIONREAD = 0;
        F_DUPFD = 0;
        F_DUPFD_CLOEXEC = 0;
        F_GETFD = 0;
        F_GETFL = 0;
        F_GETLK = 0;
        F_GETLK64 = 0;
        F_GETOWN = 0;
        F_OK = 0;
        F_RDLCK = 0;
        F_SETFD = 0;
        F_SETFL = 0;
        F_SETLK = 0;
        F_SETLK64 = 0;
        F_SETLKW = 0;
        F_SETLKW64 = 0;
        F_SETOWN = 0;
        F_UNLCK = 0;
        F_WRLCK = 0;
        IFA_F_DADFAILED = 0;
        IFA_F_DEPRECATED = 0;
        IFA_F_HOMEADDRESS = 0;
        IFA_F_NODAD = 0;
        IFA_F_OPTIMISTIC = 0;
        IFA_F_PERMANENT = 0;
        IFA_F_SECONDARY = 0;
        IFA_F_TEMPORARY = 0;
        IFA_F_TENTATIVE = 0;
        IFF_ALLMULTI = 0;
        IFF_AUTOMEDIA = 0;
        IFF_BROADCAST = 0;
        IFF_DEBUG = 0;
        IFF_DYNAMIC = 0;
        IFF_LOOPBACK = 0;
        IFF_MASTER = 0;
        IFF_MULTICAST = 0;
        IFF_NOARP = 0;
        IFF_NOTRAILERS = 0;
        IFF_POINTOPOINT = 0;
        IFF_PORTSEL = 0;
        IFF_PROMISC = 0;
        IFF_RUNNING = 0;
        IFF_SLAVE = 0;
        IFF_UP = 0;
        IPPROTO_ICMP = 0;
        IPPROTO_ICMPV6 = 0;
        IPPROTO_IP = 0;
        IPPROTO_IPV6 = 0;
        IPPROTO_RAW = 0;
        IPPROTO_TCP = 0;
        IPPROTO_UDP = 0;
        IPV6_CHECKSUM = 0;
        IPV6_MULTICAST_HOPS = 0;
        IPV6_MULTICAST_IF = 0;
        IPV6_MULTICAST_LOOP = 0;
        IPV6_RECVDSTOPTS = 0;
        IPV6_RECVHOPLIMIT = 0;
        IPV6_RECVHOPOPTS = 0;
        IPV6_RECVPKTINFO = 0;
        IPV6_RECVRTHDR = 0;
        IPV6_RECVTCLASS = 0;
        IPV6_TCLASS = 0;
        IPV6_UNICAST_HOPS = 0;
        IPV6_V6ONLY = 0;
        IP_MULTICAST_IF = 0;
        IP_MULTICAST_LOOP = 0;
        IP_MULTICAST_TTL = 0;
        IP_TOS = 0;
        IP_TTL = 0;
        MAP_FIXED = 0;
        MAP_PRIVATE = 0;
        MAP_SHARED = 0;
        MCAST_BLOCK_SOURCE = 0;
        MCAST_JOIN_GROUP = 0;
        MCAST_JOIN_SOURCE_GROUP = 0;
        MCAST_LEAVE_GROUP = 0;
        MCAST_LEAVE_SOURCE_GROUP = 0;
        MCAST_UNBLOCK_SOURCE = 0;
        MCL_CURRENT = 0;
        MCL_FUTURE = 0;
        MSG_CTRUNC = 0;
        MSG_DONTROUTE = 0;
        MSG_EOR = 0;
        MSG_OOB = 0;
        MSG_PEEK = 0;
        MSG_TRUNC = 0;
        MSG_WAITALL = 0;
        MS_ASYNC = 0;
        MS_INVALIDATE = 0;
        MS_SYNC = 0;
        NI_DGRAM = 0;
        NI_NAMEREQD = 0;
        NI_NOFQDN = 0;
        NI_NUMERICHOST = 0;
        NI_NUMERICSERV = 0;
        O_ACCMODE = 0;
        O_APPEND = 0;
        O_CLOEXEC = 0;
        O_CREAT = 0;
        O_DSYNC = 0;
        O_EXCL = 0;
        O_NOCTTY = 0;
        O_NOFOLLOW = 0;
        O_NONBLOCK = 0;
        O_RDONLY = 0;
        O_RDWR = 0;
        O_SYNC = 0;
        O_TRUNC = 0;
        O_WRONLY = 0;
        POLLERR = 0;
        POLLHUP = 0;
        POLLIN = 0;
        POLLNVAL = 0;
        POLLOUT = 0;
        POLLPRI = 0;
        POLLRDBAND = 0;
        POLLRDNORM = 0;
        POLLWRBAND = 0;
        POLLWRNORM = 0;
        PROT_EXEC = 0;
        PROT_NONE = 0;
        PROT_READ = 0;
        PROT_WRITE = 0;
        PR_GET_DUMPABLE = 0;
        PR_SET_DUMPABLE = 0;
        PR_SET_NO_NEW_PRIVS = 0;
        RT_SCOPE_HOST = 0;
        RT_SCOPE_LINK = 0;
        RT_SCOPE_NOWHERE = 0;
        RT_SCOPE_SITE = 0;
        RT_SCOPE_UNIVERSE = 0;
        R_OK = 0;
        SEEK_CUR = 0;
        SEEK_END = 0;
        SEEK_SET = 0;
        SHUT_RD = 0;
        SHUT_RDWR = 0;
        SHUT_WR = 0;
        SIGABRT = 0;
        SIGALRM = 0;
        SIGBUS = 0;
        SIGCHLD = 0;
        SIGCONT = 0;
        SIGFPE = 0;
        SIGHUP = 0;
        SIGILL = 0;
        SIGINT = 0;
        SIGIO = 0;
        SIGKILL = 0;
        SIGPIPE = 0;
        SIGPROF = 0;
        SIGPWR = 0;
        SIGQUIT = 0;
        SIGRTMAX = 0;
        SIGRTMIN = 0;
        SIGSEGV = 0;
        SIGSTKFLT = 0;
        SIGSTOP = 0;
        SIGSYS = 0;
        SIGTERM = 0;
        SIGTRAP = 0;
        SIGTSTP = 0;
        SIGTTIN = 0;
        SIGTTOU = 0;
        SIGURG = 0;
        SIGUSR1 = 0;
        SIGUSR2 = 0;
        SIGVTALRM = 0;
        SIGWINCH = 0;
        SIGXCPU = 0;
        SIGXFSZ = 0;
        SIOCGIFADDR = 0;
        SIOCGIFBRDADDR = 0;
        SIOCGIFDSTADDR = 0;
        SIOCGIFNETMASK = 0;
        SOCK_DGRAM = 0;
        SOCK_RAW = 0;
        SOCK_SEQPACKET = 0;
        SOCK_STREAM = 0;
        SOL_SOCKET = 0;
        SO_BINDTODEVICE = 0;
        SO_BROADCAST = 0;
        SO_DEBUG = 0;
        SO_DONTROUTE = 0;
        SO_ERROR = 0;
        SO_KEEPALIVE = 0;
        SO_LINGER = 0;
        SO_OOBINLINE = 0;
        SO_PASSCRED = 0;
        SO_PEERCRED = 0;
        SO_RCVBUF = 0;
        SO_RCVLOWAT = 0;
        SO_RCVTIMEO = 0;
        SO_REUSEADDR = 0;
        SO_SNDBUF = 0;
        SO_SNDLOWAT = 0;
        SO_SNDTIMEO = 0;
        SO_TYPE = 0;
        STDERR_FILENO = 0;
        STDIN_FILENO = 0;
        STDOUT_FILENO = 0;
        ST_MANDLOCK = 0;
        ST_NOATIME = 0;
        ST_NODEV = 0;
        ST_NODIRATIME = 0;
        ST_NOEXEC = 0;
        ST_NOSUID = 0;
        ST_RDONLY = 0;
        ST_RELATIME = 0;
        ST_SYNCHRONOUS = 0;
        S_IFBLK = 0;
        S_IFCHR = 0;
        S_IFDIR = 0;
        S_IFIFO = 0;
        S_IFLNK = 0;
        S_IFMT = 0;
        S_IFREG = 0;
        S_IFSOCK = 0;
        S_IRGRP = 0;
        S_IROTH = 0;
        S_IRUSR = 0;
        S_IRWXG = 0;
        S_IRWXO = 0;
        S_IRWXU = 0;
        S_ISGID = 0;
        S_ISUID = 0;
        S_ISVTX = 0;
        S_IWGRP = 0;
        S_IWOTH = 0;
        S_IWUSR = 0;
        S_IXGRP = 0;
        S_IXOTH = 0;
        S_IXUSR = 0;
        TCP_NODELAY = 0;
        TCP_USER_TIMEOUT = 0;
        WCONTINUED = 0;
        WEXITED = 0;
        WNOHANG = 0;
        WNOWAIT = 0;
        WSTOPPED = 0;
        WUNTRACED = 0;
        W_OK = 0;
        X_OK = 0;
        _SC_2_CHAR_TERM = 0;
        _SC_2_C_BIND = 0;
        _SC_2_C_DEV = 0;
        _SC_2_C_VERSION = 0;
        _SC_2_FORT_DEV = 0;
        _SC_2_FORT_RUN = 0;
        _SC_2_LOCALEDEF = 0;
        _SC_2_SW_DEV = 0;
        _SC_2_UPE = 0;
        _SC_2_VERSION = 0;
        _SC_AIO_LISTIO_MAX = 0;
        _SC_AIO_MAX = 0;
        _SC_AIO_PRIO_DELTA_MAX = 0;
        _SC_ARG_MAX = 0;
        _SC_ASYNCHRONOUS_IO = 0;
        _SC_ATEXIT_MAX = 0;
        _SC_AVPHYS_PAGES = 0;
        _SC_BC_BASE_MAX = 0;
        _SC_BC_DIM_MAX = 0;
        _SC_BC_SCALE_MAX = 0;
        _SC_BC_STRING_MAX = 0;
        _SC_CHILD_MAX = 0;
        _SC_CLK_TCK = 0;
        _SC_COLL_WEIGHTS_MAX = 0;
        _SC_DELAYTIMER_MAX = 0;
        _SC_EXPR_NEST_MAX = 0;
        _SC_FSYNC = 0;
        _SC_GETGR_R_SIZE_MAX = 0;
        _SC_GETPW_R_SIZE_MAX = 0;
        _SC_IOV_MAX = 0;
        _SC_JOB_CONTROL = 0;
        _SC_LINE_MAX = 0;
        _SC_LOGIN_NAME_MAX = 0;
        _SC_MAPPED_FILES = 0;
        _SC_MEMLOCK = 0;
        _SC_MEMLOCK_RANGE = 0;
        _SC_MEMORY_PROTECTION = 0;
        _SC_MESSAGE_PASSING = 0;
        _SC_MQ_OPEN_MAX = 0;
        _SC_MQ_PRIO_MAX = 0;
        _SC_NGROUPS_MAX = 0;
        _SC_NPROCESSORS_CONF = 0;
        _SC_NPROCESSORS_ONLN = 0;
        _SC_OPEN_MAX = 0;
        _SC_PAGESIZE = 0;
        _SC_PAGE_SIZE = 0;
        _SC_PASS_MAX = 0;
        _SC_PHYS_PAGES = 0;
        _SC_PRIORITIZED_IO = 0;
        _SC_PRIORITY_SCHEDULING = 0;
        _SC_REALTIME_SIGNALS = 0;
        _SC_RE_DUP_MAX = 0;
        _SC_RTSIG_MAX = 0;
        _SC_SAVED_IDS = 0;
        _SC_SEMAPHORES = 0;
        _SC_SEM_NSEMS_MAX = 0;
        _SC_SEM_VALUE_MAX = 0;
        _SC_SHARED_MEMORY_OBJECTS = 0;
        _SC_SIGQUEUE_MAX = 0;
        _SC_STREAM_MAX = 0;
        _SC_SYNCHRONIZED_IO = 0;
        _SC_THREADS = 0;
        _SC_THREAD_ATTR_STACKADDR = 0;
        _SC_THREAD_ATTR_STACKSIZE = 0;
        _SC_THREAD_DESTRUCTOR_ITERATIONS = 0;
        _SC_THREAD_KEYS_MAX = 0;
        _SC_THREAD_PRIORITY_SCHEDULING = 0;
        _SC_THREAD_PRIO_INHERIT = 0;
        _SC_THREAD_PRIO_PROTECT = 0;
        _SC_THREAD_SAFE_FUNCTIONS = 0;
        _SC_THREAD_STACK_MIN = 0;
        _SC_THREAD_THREADS_MAX = 0;
        _SC_TIMERS = 0;
        _SC_TIMER_MAX = 0;
        _SC_TTY_NAME_MAX = 0;
        _SC_TZNAME_MAX = 0;
        _SC_VERSION = 0;
        _SC_XBS5_ILP32_OFF32 = 0;
        _SC_XBS5_ILP32_OFFBIG = 0;
        _SC_XBS5_LP64_OFF64 = 0;
        _SC_XBS5_LPBIG_OFFBIG = 0;
        _SC_XOPEN_CRYPT = 0;
        _SC_XOPEN_ENH_I18N = 0;
        _SC_XOPEN_LEGACY = 0;
        _SC_XOPEN_REALTIME = 0;
        _SC_XOPEN_REALTIME_THREADS = 0;
        _SC_XOPEN_SHM = 0;
        _SC_XOPEN_UNIX = 0;
        _SC_XOPEN_VERSION = 0;
        _SC_XOPEN_XCU_VERSION = 0;
    }
}
