package android.icu.text;

public enum Error
{
    BIDI, 
    CONTEXTJ, 
    CONTEXTO_DIGITS, 
    CONTEXTO_PUNCTUATION, 
    DISALLOWED, 
    DOMAIN_NAME_TOO_LONG, 
    EMPTY_LABEL, 
    HYPHEN_3_4, 
    INVALID_ACE_LABEL, 
    LABEL_HAS_DOT, 
    LABEL_TOO_LONG, 
    LEADING_COMBINING_MARK, 
    LEADING_HYPHEN, 
    PUNYCODE, 
    TRAILING_HYPHEN;
}
