package android.icu.text;

public enum Style
{
    EXEMPLAR_LOCATION, 
    GENERIC_LOCATION, 
    GENERIC_LONG, 
    GENERIC_SHORT, 
    ISO_BASIC_FIXED, 
    ISO_BASIC_FULL, 
    ISO_BASIC_LOCAL_FIXED, 
    ISO_BASIC_LOCAL_FULL, 
    ISO_BASIC_LOCAL_SHORT, 
    ISO_BASIC_SHORT, 
    ISO_EXTENDED_FIXED, 
    ISO_EXTENDED_FULL, 
    ISO_EXTENDED_LOCAL_FIXED, 
    ISO_EXTENDED_LOCAL_FULL, 
    LOCALIZED_GMT, 
    LOCALIZED_GMT_SHORT, 
    SPECIFIC_LONG, 
    SPECIFIC_SHORT, 
    ZONE_ID, 
    ZONE_ID_SHORT;
}
